manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Cyboard-DigitalTailor
      url-base: https://github.com/Cyboard-DigitalTailor
    - name: dreadvimfantail
      url-base: https://github.com/dreadvimfantail
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboards
      remote: dreadvimfantail
      repo-path: zmk-keyboards-imprint
      revision: main
      import: config/west.yml
  self:
    path: config
